export const BASE_URL = "http://localhost:5034"
export const UPLOAD_PATH = "/upload"
export const QUERY_PATH = "/query"
export const LIST_DOCUMENTS_PATH = "/documents"
export const YOUTUBE_DOCUMENT_TIME_DATA_PATH = "/document/youtube-time-data"
